--
-- Author: James Pool
-- ONID: 932664412
-- OSU Email: poolj@oregonstate.edu
-- Initial Creation: 28 February 2016
--
-- Filename: mlp-fim-schema.sql
-- Description: Schema creation document for final project
-- 

--
-- Table structure for table 'mlp_pony'
--
CREATE TABLE mlp_pony (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	cutieMark VARCHAR(255) NOT NULL,
	coatColor BINARY(24) NOT NULL,
	maneColor BINARY(24) NOT NULL,
	eyeColor BINARY(24) NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_type'
--
CREATE TABLE mlp_type (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	wings BOOLEAN NOT NULL,
	horn BOOLEAN NOT NULL,
	ability VARCHAR(255) NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_location'
--
CREATE TABLE mlp_location (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_occupation'
--
CREATE TABLE mlp_occupation (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	place VARCHAR(255) NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for relationship table 'mlp_ponyType'
--
CREATE TABLE mlp_ponyType (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	ponyID SMALLINT UNSIGNED NOT NULL,
	typeID SMALLINT UNSIGNED NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (ponyID) REFERENCES mlp_pony(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (typeID) REFERENCES mlp_type(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table struct for relationship table 'mlp_ponyLocation'
--
CREATE TABLE mlp_ponyLocation (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	ponyID SMALLINT UNSIGNED NOT NULL,
	locationID SMALLINT UNSIGNED NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (ponyID) REFERENCES mlp_pony(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (locationID) REFERENCES mlp_location(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for relationship table 'mlp_ponyOccupation'
--
CREATE TABLE mlp_ponyOccupation (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	ponyID SMALLINT UNSIGNED NOT NULL,
	occupationID SMALLINT UNSIGNED NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (ponyID) REFERENCES mlp_pony(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (occupationID) REFERENCES mlp_occupation(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for relationship table 'mlp_ponyChild'
--
CREATE TABLE mlp_ponyChild (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	ponyID SMALLINT UNSIGNED NOT NULL,
	childID SMALLINT UNSIGNED,  -- Can Be NULL
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (ponyID) REFERENCES mlp_pony(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (childID) REFERENCES mlp_pony(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;