--
-- Author: James Pool
-- ONID: 932664412
-- OSU Email: poolj@oregonstate.edu
-- Initial Creation: 28 February 2016
--
-- Filename: mlp-fim-schema.sql
-- Description: Schema creation document for final project
-- 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

--
-- Table structure for table 'mlp_pony'
--
CREATE TABLE mlp_pony (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	gender CHAR(1) NOT NULL,
	cutieMark VARCHAR(255) NOT NULL,
	typeID SMALLINT UNSIGNED,
	residanceID SMALLINT UNSIGNED,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (typeID) REFERENCES mlp_type(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_type'
--
CREATE TABLE mlp_type (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	wings BOOLEAN NOT NULL,
	horn BOOLEAN NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_residance'
--
CREATE TABLE mlp_residance (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	locationID SMALLINT UNSIGNED,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (locationID) REFERENCES mlp_location(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_location'
--
CREATE TABLE mlp_location (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_occupation'
--
CREATE TABLE mlp_occupation (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (title)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'mlp_color'
--
CREATE TABLE mlp_color (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	hexCode CHAR(6) NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (name, hexCode)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for relationship table 'mlp_ponyOccupation'
--
CREATE TABLE mlp_ponyOccupation (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	ponyID SMALLINT UNSIGNED NOT NULL,
	occupationID SMALLINT UNSIGNED NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (ponyID) REFERENCES mlp_pony(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (occupationID) REFERENCES mlp_occupation(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for relationship table 'mlp_ponyColor'
--
CREATE TABLE mlp_ponyColor (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	area VARCHAR(255) NOT NULL,
	ponyID SMALLINT UNSIGNED NOT NULL,
	colorID SMALLINT UNSIGNED NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (ponyID) REFERENCES mlp_pony(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (colorID) REFERENCES mlp_color(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;